---
latitude: 37.78078
longitude: -122.41217
name: Aida Plaza Hotel
email: victor@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 1087 Market Street
  street2: ''
  state: California
  city: San Francisco
  country: United States
  zip_code: '94103'
_hotel_id: AID446
_portal_id: required-but-empty
_root_path: https://qa4.ttaws.com/rt
logo: Aida Plaza Hotel
